### ISSUE TITLE
link in file info.xml doens't work

### ISSUE THREAD

**Issue by pierrefrancois** [eileenmcnaughton/nz.co.fuzion.cssinline#10]
The link reported as Feedback or discussion under the &lt;comments&gt;...&lt;/comments&gt; tag in the file **info.xml** is not working:

[http://forum.civicrm.org/index.php/topic,30771.msg132064.html#msg132064](http://forum.civicrm.org/index.php/topic,30771.msg132064.html#msg132064)

Error: 404 Not Found

**Comment by eileenmcnaughton** [comment]
I removed that link - but we don't really have an alternative place to look
