### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'CSSIN.php'

### ISSUE THREAD

**Issue by francescbassas** [eileenmcnaughton/nz.co.fuzion.cssinline#2]
I don't know if it is an issue but I recently upgrade CiviCRM to 4.7.10 and when Send Scheduled Mailings cron job runs I get this error:

`Fatal error: require_once(): Failed opening required 'CSSIN.php'`

I workaround this by patching line104 of cssinline.php from

`require_once 'CSSIN.php';`

to

`require_once 'packages/cssin/src/CSSIN.php';`

**Comment by eileenmcnaughton** [comment]
I'm happy to merge that if you want to put it up as a patch

**Comment by francescbassas** [comment]
Sorry eileen. I just saw the error came from an unwanted change in my code :sweat_smile:
